#!/bin/bash

# This munki condition script fill the ConditionalItems plist with list of existing printers queue name.
# Usefull if you want to install a package with Munki only if mcx_0 is here (to apply custom options for example).

ad_key="ad_domain"

# Read the location of the ManagedInstallDir from ManagedInstall.plist
managedinstalldir="$(defaults read /Library/Preferences/ManagedInstalls ManagedInstallDir)"

if [ "$managedinstalldir" = "" ]; then
	echo "No Managed Installs directory could be read, exiting.."
	exit 1
fi

# Make sure we're outputting our information to "ConditionalItems.plist" (plist is left off since defaults requires this)
plist_loc="$managedinstalldir/ConditionalItems"

current_domain=$(dsconfigad -show | grep "Active Directory Domain" | awk -F" = " '{print $2}' | dsconfigad -show | grep "Active Directory Domain" | awk -F" = " '{print $2}')

defaults write "$plist_loc" "$ad_key" -string "$current_domain"

exit 0
